### ISSUE TITLE
Small fixes in flux product

### ISSUE THREAD

**Issue by koren007** [EXCITED-CO2/excited-workflow#26]
- [ ] great lakes region uitknippen (ERA5 land-sea mask)
- [x] center at month before interpolating
- [x] check locaties van grid cellen (bounds/centers)

**Comment by BSchilperoort** [comment]
**check locaties van grid cellen (bounds/centers)**

- ERA5: center of tile
- CarbonTracker: center of tile
- biomass dataset: center of tile
- MODIS NIRV: center of tile
- SPEI: center of tile

**Comment by BSchilperoort** [comment]
> center at month before interpolating
This is now implemented too

**Comment by BSchilperoort** [comment]
@ClaireDons you can mark this as closed when you have removed the great lakes
